name: dev

on:
  push:
    branches: [dev]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: Build
        run: docker build . -t 5scontrol/onvif:latest

      - name: Push
        run: docker push 5scontrol/onvif:latest

      - name: deploy
        run: curl 192.168.1.115:4545/deploy-pod?service=onvif  
